import type { GetServerSideProps, NextPage } from "next";
import { PrismaClient } from "@prisma/client";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

type RoomInfo = {
  value: number;
  createdAt: number;
};

type MotionInfo = {
  createdAt: number;
};

type ServerProps = {
  rooms: {
    name: string;
    temperatures: RoomInfo[];
    humidities: RoomInfo[];
    lights: RoomInfo[];
    motions: MotionInfo[];
  }[];
};

const Home = ({ rooms }: ServerProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>お部屋の情報</h1>

        {rooms.map((room) => (
          <>
            <h2>{room.name}</h2>
            <div>
              <p>温度</p>
              <ul>
                {room.temperatures.map((item) => (
                  <li key={item.createdAt}>{item.value}</li>
                ))}
              </ul>
            </div>
            <div>
              <p>湿度</p>
              <ul>
                {room.humidities.map((item) => (
                  <li key={item.createdAt}>{item.value}</li>
                ))}
              </ul>
            </div>
            <div>
              <p>明るさ</p>
              <ul>
                {room.lights.map((item) => (
                  <li key={item.createdAt}>{item.value}</li>
                ))}
              </ul>
            </div>
            <div>
              <p>人感センサー</p>
              <ul>
                {room.motions.map((item) => (
                  <li key={item.createdAt}>{item.createdAt}</li>
                ))}
              </ul>
            </div>
          </>
        ))}
      </main>
    </div>
  );
};

export default Home;
export const getServerSideProps: GetServerSideProps<ServerProps> = async (
  context
) => {
  const prisma = new PrismaClient();

  const rooms = await prisma.room.findMany({
    include: {
      motions: true,
      humidities: true,
      lights: true,
      temperatures: true,
    },
  });

  return {
    props: {
      rooms: rooms.map((room) => ({
        name: room.name,
        humidities: room.humidities.map((item) => ({
          value: item.humidity,
          createdAt: item.created_at.getTime(),
        })),
        temperatures: room.temperatures.map((item) => ({
          value: item.temperature,
          createdAt: item.created_at.getTime(),
        })),
        motions: room.motions.map((item) => ({
          createdAt: item.created_at.getTime(),
        })),
        lights: room.lights.map((item) => ({
          value: item.light,
          createdAt: item.created_at.getTime(),
        })),
      })),
    },
  };
};
